<a href="https://colab.research.google.com/github/Git-Vivek-Gupta/Warehouse-SLA-Risk-Analytics-Automated-Alerting-System/blob/main/Python%20Notebooks%20(Colab)/Warehouse_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
path = '/content/drive/MyDrive/Colab Notebooks/Warehouse/raw/picklist_creation_data_for_hackathon_with_order_date.csv'

Mounted at /content/drive

In [ ]:
PROJECT_PATH = "/content/drive/MyDrive/Colab Notebooks/Warehouse"
import os
os.listdir(PROJECT_PATH)

['raw', 'Warehouse data cleaning.ipynb']

In [ ]:
import pandas as pd

file_path = PROJECT_PATH + "/raw/picklist_creation_data_for_hackathon_with_order_date.csv"

df = pd.read_csv(file_path)

In [ ]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

print("\nData types:")
display(df.dtypes)

Shape: (1281177, 20)

Columns:
['dt', 'order_date', 'location_code', 'order_id', 'sku', 'order_qty', 'bin', 'zone', 'bin_rank', 'order_tag', 'store_id', 'floor', 'rack', 'aisle', 'pods_per_picklist_in_that_zone', 'length_in_cm', 'width_in_cm', 'height_in_cm', 'weight_in_grams', 'pod_priority']

First 5 rows:

,dt,order_date,location_code,order_id,sku,order_qty,bin,zone,bin_rank,order_tag,store_id,floor,rack,aisle,pods_per_picklist_in_that_zone,length_in_cm,width_in_cm,height_in_cm,weight_in_grams,pod_priority
0,2025-12-08,2025-11-13,BLR,BLR_129701,25739.0,1.0,LD-AA-G2-A2-A1-08-D,combo_9,3568,Normal,396467.0,G2,AA,LD,4,5.0,18.0,2.0,160.0,P3
1,2025-12-08,2025-11-13,BLR,BLR_129728,25739.0,4.0,LD-AA-G2-A2-A1-08-D,combo_9,3568,Normal,394542.0,G2,AA,LD,4,5.0,18.0,2.0,160.0,P2
2,2025-12-08,2025-11-09,BLR,BLR_128152,133576.0,2.0,LD-AA-G2-A2-A1-16-B,combo_9,3590,Normal,400418.0,G2,AA,LD,4,11.0,4.0,14.0,100.0,P5
3,2025-12-08,2025-11-09,BLR,BLR_128140,133576.0,2.0,LD-AA-G2-A2-A1-16-B,combo_9,3590,Normal,394957.0,G2,AA,LD,4,11.0,4.0,14.0,100.0,P1
4,2025-12-08,2025-11-21,BLR,BLR_122508,9599.0,3.0,LD-AA-G3-A3-A1-10-D,combo_11,5935,Normal,400356.0,G3,AA,LD,6,23.5,18.0,1.8,1.0,P2

Data types:

dt                                 object
order_date                         object
location_code                      object
order_id                           object
sku                               float64
order_qty                         float64
bin                                object
zone                               object
bin_rank                            int64
order_tag                          object
store_id                          float64
floor                              object
rack                               object
aisle                              object
pods_per_picklist_in_that_zone      int64
length_in_cm                      float64
width_in_cm                       float64
height_in_cm                      float64
weight_in_grams                   float64
pod_priority                       object
dtype: object

In [ ]:
print("Missing values:")
display(df.isnull().sum())

print("Duplicate rows:", df.duplicated().sum())

Missing values:

dt                                   0
order_date                           0
location_code                        0
order_id                             0
sku                                  0
order_qty                            0
bin                                  0
zone                                 0
bin_rank                             0
order_tag                            0
store_id                             0
floor                             6545
rack                              6545
aisle                             6545
pods_per_picklist_in_that_zone       0
length_in_cm                         0
width_in_cm                          0
height_in_cm                         0
weight_in_grams                      0
pod_priority                         0
dtype: int64

Duplicate rows: 0

In [ ]:
print("Min date:", df["order_date"].min())
print("Max date:", df["order_date"].max())

Min date: 2025-11-08
Max date: 2025-12-08

In [ ]:
print("Unique orders:", df["order_id"].nunique())
print("Unique SKUs:", df["sku"].nunique())
print("Unique stores:", df["store_id"].nunique())
print("Unique bins:", df["bin"].nunique())
print("Unique zones:", df["zone"].nunique())

print("\nOrder tags:")
print(df["order_tag"].value_counts())

print("\nPod priorities:")
print(df["pod_priority"].value_counts())

print("\nLocations:")
print(df["location_code"].value_counts())

Unique orders: 1901
Unique SKUs: 21183
Unique stores: 48
Unique bins: 35530
Unique zones: 38

Order tags:
order_tag
Normal    1281177
Name: count, dtype: int64

Pod priorities:
pod_priority
P3    351402
P2    320251
P5    292803
P1    270558
P4     18230
P9     17466
P6     10467
Name: count, dtype: int64

Locations:
location_code
BLR    1281177
Name: count, dtype: int64

In [ ]:
df.groupby('order_id')['pod_priority'].nunique().value_counts()

pod_priority
1    1876
2      25
Name: count, dtype: int64

In [ ]:
df.groupby('order_id').size().describe()

count    1901.000000
mean      673.948974
std       568.748899
min         1.000000
25%       237.000000
50%       636.000000
75%       973.000000
max      3812.000000
dtype: float64

In [ ]:
order_summary = df.groupby("order_id").agg(
    rows=("order_id", "size"),
    unique_skus=("sku", "nunique"),
    total_qty=("order_qty", "sum"),
    zones=("zone", "nunique"),
    bins=("bin", "nunique")
)

display(order_summary.describe())

              rows  unique_skus     total_qty        zones         bins
count  1901.000000  1901.000000   1901.000000  1901.000000  1901.000000
mean    673.948974   611.490794   2144.815886    26.934771   645.691215
std     568.748899   498.615795   1990.088388    12.354073   531.302130
min       1.000000     1.000000      1.000000     1.000000     1.000000
25%     237.000000   226.000000    569.000000    28.000000   232.000000
50%     636.000000   587.000000   1874.000000    33.000000   621.000000
75%     973.000000   883.000000   3109.000000    34.000000   943.000000
max    3812.000000  2804.000000  16379.000000    37.000000  3436.000000

In [ ]:
display(order_summary.sort_values("rows", ascending=False).head(10))

            rows  unique_skus  total_qty  zones  bins
order_id
BLR_122236  3812         2742     8485.0     35  3436
BLR_120620  3219         2680    10474.0     34  2890
BLR_122233  3167         2788     7184.0     36  2868
BLR_122268  3135         2626    16379.0     34  2841
BLR_122524  3134         2714     9617.0     36  2855
BLR_128126  3114         2742     9509.0     35  2854
BLR_125045  3108         2633    11953.0     35  2861
BLR_126050  3102         2605    12565.0     36  2791
BLR_129739  3085         2601    13056.0     35  2775
BLR_127825  3044         2684     8565.0     36  2818

In [ ]:
print(df.groupby("order_id")["order_date"].nunique().describe())
print(df.groupby("order_id")["dt"].nunique().describe())
print(df.groupby("order_id")["store_id"].nunique().describe())
print(df.groupby("order_id")["pod_priority"].nunique().describe())

count    1901.000000
mean        1.015255
std         0.122598
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000
Name: order_date, dtype: float64
count    1901.0
mean        1.0
std         0.0
min         1.0
25%         1.0
50%         1.0
75%         1.0
max         1.0
Name: dt, dtype: float64
count    1901.000000
mean        1.014203
std         0.118358
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000
Name: store_id, dtype: float64
count    1901.000000
mean        1.013151
std         0.113951
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         2.000000
Name: pod_priority, dtype: float64

In [ ]:
display(
    df.groupby("order_id")
      .agg(
          order_date=("order_date", "first"),
          dt=("dt", "first"),
          store=("store_id", "nunique"),
          priorities=("pod_priority", "nunique")
      )
      .head(10)
)

            order_date          dt  store  priorities
order_id
BLR_120033  2025-11-14  2025-12-08      1           1
BLR_120034  2025-11-14  2025-12-08      1           1
BLR_120035  2025-11-14  2025-12-08      1           1
BLR_120036  2025-11-14  2025-12-08      1           1
BLR_120037  2025-11-14  2025-12-08      1           1
BLR_120038  2025-11-14  2025-12-08      1           1
BLR_120039  2025-11-14  2025-12-08      1           1
BLR_120040  2025-11-14  2025-12-08      1           1
BLR_120041  2025-11-14  2025-12-08      1           1
BLR_120042  2025-11-14  2025-12-08      1           1

In [ ]:
order_check = df.groupby("order_id").agg(
    dates=("order_date", "nunique"),
    stores=("store_id", "nunique"),
    priorities=("pod_priority", "nunique")
)

exceptions = order_check[
    (order_check["dates"] > 1) |
    (order_check["stores"] > 1) |
    (order_check["priorities"] > 1)
]

print("Exceptions:", len(exceptions))
display(exceptions.head(20))

Exceptions: 29

            dates  stores  priorities
order_id
BLR_128159      2       2           2
BLR_128160      2       2           2
BLR_128161      2       2           2
BLR_128162      2       2           2
BLR_128163      2       2           2
BLR_128164      2       2           2
BLR_128165      2       2           2
BLR_128166      2       2           2
BLR_128168      2       2           2
BLR_128170      2       1           1
BLR_128174      2       2           2
BLR_128175      2       2           2
BLR_128176      2       2           2
BLR_128178      2       2           2
BLR_128179      2       2           2
BLR_128726      2       2           1
BLR_128727      2       2           2
BLR_128729      2       2           2
BLR_128736      2       2           2
BLR_128737      2       2           2

In [ ]:
display(
    df[df["order_id"].isin(exceptions.index)]
    [["order_id", "order_date", "store_id", "pod_priority", "sku", "zone"]]
    .head(50)
)

        order_id  order_date  store_id pod_priority       sku        zone
9     BLR_128178  2025-11-09  400061.0           P2    4107.0     CICO_G2
36    BLR_128178  2025-11-09  400061.0           P2  248210.0  SPICES&DAL
114   BLR_128749  2025-11-11  351426.0           P4   13549.0     combo_8
241   BLR_128160  2025-12-06  398939.0           P1   34413.0     combo_4
265   BLR_128179  2025-12-06  392645.0           P2  244132.0     combo_4
274   BLR_128726  2025-12-08  396766.0           P5    4700.0   H_STAPLES
335   BLR_128737  2025-11-11  401309.0           P3   21016.0     combo_8
341   BLR_128746  2025-11-11  398693.0           P1    5243.0     combo_8
482   BLR_128743  2025-12-08  394413.0           P3  136359.0     combo_9
485   BLR_128160  2025-12-06  398939.0           P1    9580.0     combo_9
488   BLR_128736  2025-11-11  398161.0           P5    7622.0     combo_9
513   BLR_128163  2025-11-09  395106.0           P1  114606.0     combo_8
514   BLR_128160  2025-12-06  398939.0           P1   15821.0     combo_8
550   BLR_128170  2025-11-09  396446.0           P3    5243.0    combo_11
626   BLR_128729  2025-12-08  394542.0           P2    6078.0     combo_9
679   BLR_128749  2025-11-11  351426.0           P4    4210.0     STAPLES
702   BLR_128160  2025-12-06  398939.0           P1   67504.0     CICO_G2
720   BLR_128741  2025-12-08  398693.0           P1   11631.0     combo_6
743   BLR_128161  2025-12-06  396766.0           P5  236397.0  FMCG_FOOD1
758   BLR_128168  2025-12-06  401063.0           P1    1290.0  FMCG_FOOD1
779   BLR_128746  2025-11-11  398693.0           P1    4990.0    combo_11
844   BLR_128744  2025-11-11  398161.0           P2   17588.0     combo_7
869   BLR_128741  2025-12-08  398693.0           P1    7622.0     combo_9
940   BLR_128750  2025-12-08  400357.0           P1  240991.0    BISC_BAK
949   BLR_128165  2025-11-09  399370.0           P2     845.0     combo_6
968   BLR_128160  2025-11-09  399046.0           P5  178487.0  SPICES&DAL
969   BLR_128168  2025-11-09  400156.0           P3  178487.0  SPICES&DAL
1011  BLR_128741  2025-12-08  398693.0           P1    2623.0     combo_6
1033  BLR_128729  2025-12-08  394542.0           P2  136359.0    BISC_BAK
1063  BLR_128738  2025-12-08  396204.0           P2  142041.0     combo_6
1130  BLR_128175  2025-12-06  397205.0           P1     839.0  CHOCOLATES
1150  BLR_128162  2025-12-06  400418.0           P5   13940.0  HVAL_APPG1
1164  BLR_128750  2025-12-08  400357.0           P1     767.0  CHOCOLATES
1190  BLR_128160  2025-11-09  399046.0           P5    4196.0   H_STAPLES
1197  BLR_128160  2025-12-06  398939.0           P1    4700.0   H_STAPLES
1222  BLR_128741  2025-12-08  398693.0           P1   11906.0     combo_5
1251  BLR_128737  2025-11-11  401309.0           P3    5002.0     combo_5
1261  BLR_128736  2025-12-08  401063.0           P1   25758.0   H_STAPLES
1462  BLR_128175  2025-12-06  397205.0           P1     630.0     combo_9
1498  BLR_128174  2025-12-06  395468.0           P3  231222.0  FMCG_FOOD2
1513  BLR_128164  2025-12-06  400490.0           P5     403.0     combo_9
1523  BLR_128737  2025-12-08  394577.0           P2   19891.0     combo_8
1524  BLR_128163  2025-12-06  400793.0           P5   19891.0     combo_8
1601  BLR_128161  2025-11-09  400356.0           P2   90671.0     combo_8
1619  BLR_128164  2025-12-06  400490.0           P5    1684.0  FMCG_FOOD1
1622  BLR_128729  2025-12-08  394542.0           P2  226160.0  FMCG_FOOD2
1667  BLR_128749  2025-11-11  351426.0           P4   15821.0     combo_8
1690  BLR_128175  2025-12-06  397205.0           P1   13250.0  FMCG_FOOD2
1704  BLR_128161  2025-11-09  400356.0           P2  201695.0     combo_9
1707  BLR_128170  2025-11-09  396446.0           P3   39137.0     combo_9

In [ ]:
print("Zones:", df["zone"].nunique())
print("Floors:", df["floor"].nunique())
print("Racks:", df["rack"].nunique())
print("Aisles:", df["aisle"].nunique())
print("Bins:", df["bin"].nunique())
display(
    df[["zone", "floor", "rack", "aisle", "bin", "bin_rank"]]
    .head(20)
)
display(
    df.groupby("zone").agg(
        bins=("bin", "nunique"),
        avg_bin_rank=("bin_rank", "mean"),
        avg_zone_load=("pods_per_picklist_in_that_zone", "mean")
    ).sort_values("avg_zone_load", ascending=False).head(10)
)

Zones: 38
Floors: 5
Racks: 65
Aisles: 5
Bins: 35530

        zone floor rack aisle                  bin  bin_rank
0    combo_9    G2   AA    LD  LD-AA-G2-A2-A1-08-D      3568
1    combo_9    G2   AA    LD  LD-AA-G2-A2-A1-08-D      3568
2    combo_9    G2   AA    LD  LD-AA-G2-A2-A1-16-B      3590
3    combo_9    G2   AA    LD  LD-AA-G2-A2-A1-16-B      3590
4   combo_11    G3   AA    LD  LD-AA-G3-A3-A1-10-D      5935
5   combo_11    G3   AA    LD  LD-AA-G3-A3-A1-10-D      5935
6    combo_8    G3   AA    LD  LD-AA-G3-D3-D1-16-F     34100
7    combo_9    G2   AB    LD  LD-AB-G2-A2-A2-15-A      3595
8    combo_9    G2   AB    LD  LD-AB-G2-A2-A2-15-A      3595
9    CICO_G2    G2   AB    LD  LD-AB-G2-C2-C2-01-F     21559
10     DL+CL    G3   AB    LD  LD-AB-G3-C3-C2-01-D     24101
11   combo_8    G3   AB    LD  LD-AB-G3-D3-D2-06-B     34161
12   STAPLES    G1   AC    LD  LD-AC-G1-D1-D3-01-D     30799
13   STAPLES    G1   AC    LD  LD-AC-G1-D1-D3-01-D     30799
14   combo_9    G2   AC    LD  LD-AC-G2-B2-B3-10-C     15082
15  combo_11    G3   AC    LD  LD-AC-G3-A3-A3-02-A      6072
16  combo_11    G3   AC    LD  LD-AC-G3-A3-A3-08-B      6101
17  combo_11    G3   AC    LD  LD-AC-G3-A3-A3-10-F      6117
18   combo_8    G3   AC    LD  LD-AC-G3-D3-D3-04-E     34211
19   combo_8    G3   AC    LD  LD-AC-G3-E3-E3-10-E     46988

            bins  avg_bin_rank  avg_zone_load
zone
CICO_D2      533  33562.722527            7.0
CD_CICO      308  37209.849609            7.0
CICO_FD      334  12073.659599            7.0
CICO_G2     1431  22458.542615            7.0
CICO_OIL     210  18569.542947            7.0
FMCG_FOOD1   911  11415.676956            6.0
combo_4     3414  32214.388500            6.0
combo_6     2264  17118.905405            6.0
combo_10     477  18761.033727            6.0
combo_11    1984   6739.069174            6.0

In [ ]:
df[df['order_id'] == 'BLR_128178'][[
    'order_id',
    'sku',
    'order_qty',
    'zone',
    'bin',
    'bin_rank',
    'pod_priority'
]].head(20)

,order_id,sku,order_qty,zone,bin,bin_rank,pod_priority
9,BLR_128178,4107.0,14.0,CICO_G2,LD-AB-G2-C2-C2-01-F,21559,P2
36,BLR_128178,248210.0,1.0,SPICES&DAL,LD-AE-G1-A1-A5-15-F,1536,P2
1852,BLR_128178,2364.0,10.0,FMCG_FOOD1,LD-AK-G1-B1-B11-03-D,11347,P3
3188,BLR_128178,226356.0,5.0,CHOCOLATES,LD-AP-B0-B18-01-B1,8660,P3
3270,BLR_128178,10748.0,2.0,combo_2,LD-AR-E0-E20-01-E1,38787,P2
3512,BLR_128178,20126.0,3.0,combo_8,LD-AD-G3-E3-E4-09-F,46893,P2
3769,BLR_128178,31678.0,3.0,combo_11,LD-AI-G3-A3-A9-05-A,6574,P3
5801,BLR_128178,4107.0,13.0,CICO_G2,LD-AC-G2-C2-C3-04-D,21665,P2
6939,BLR_128178,1013.0,48.0,CICO_G2,LD-AD-G2-C2-C4-10-E,21714,P2
7038,BLR_128178,4649.0,25.0,STAPLES,LD-AF-G1-D1-D6-08-E,30533,P3
8287,BLR_128178,82781.0,3.0,combo_9,LD-AJ-G2-A2-A10-10-C,4275,P3
12926,BLR_128178,962.0,2.0,SPICES&DAL,LD-AM-G1-A1-A13-15-B,2023,P2
13993,BLR_128178,3451.0,5.0,combo_6,LD-AM-G3-B3-B15-09-B,16730,P3
18071,BLR_128178,15650.0,2.0,FMCG_FOOD1,LD-AG-G1-B1-B7-07-F,11742,P3
19109,BLR_128178,5821.0,3.0,combo_8,LD-AF-G3-E3-E6-09-C,46698,P2
19144,BLR_128178,7485.0,3.0,combo_8,LD-AG-G3-D3-D7-18-E,34703,P2
22104,BLR_128178,90671.0,3.0,combo_8,LD-AB-G3-D3-D2-11-B,34130,P2
23895,BLR_128178,339.0,3.0,combo_11,LD-AN-G3-A3-A14-11-D,6997,P3
25559,BLR_128178,4257.0,17.0,SPICES&DAL,LD-AJ-G1-A1-A10-13-A,1878,P2
26456,BLR_128178,88529.0,2.0,CICO_D2,LD-AG-G2-D2-D7-01-D,33397,P2

In [ ]:
df[df['order_id'] == 'BLR_128178']['zone'].nunique()

34

In [ ]:
order = df[df['order_id'] == 'BLR_128178']

order[['order_id', 'sku', 'order_qty', 'zone', 'bin', 'bin_rank', 'pod_priority']].head(20)

,order_id,sku,order_qty,zone,bin,bin_rank,pod_priority
9,BLR_128178,4107.0,14.0,CICO_G2,LD-AB-G2-C2-C2-01-F,21559,P2
36,BLR_128178,248210.0,1.0,SPICES&DAL,LD-AE-G1-A1-A5-15-F,1536,P2
1852,BLR_128178,2364.0,10.0,FMCG_FOOD1,LD-AK-G1-B1-B11-03-D,11347,P3
3188,BLR_128178,226356.0,5.0,CHOCOLATES,LD-AP-B0-B18-01-B1,8660,P3
3270,BLR_128178,10748.0,2.0,combo_2,LD-AR-E0-E20-01-E1,38787,P2
3512,BLR_128178,20126.0,3.0,combo_8,LD-AD-G3-E3-E4-09-F,46893,P2
3769,BLR_128178,31678.0,3.0,combo_11,LD-AI-G3-A3-A9-05-A,6574,P3
5801,BLR_128178,4107.0,13.0,CICO_G2,LD-AC-G2-C2-C3-04-D,21665,P2
6939,BLR_128178,1013.0,48.0,CICO_G2,LD-AD-G2-C2-C4-10-E,21714,P2
7038,BLR_128178,4649.0,25.0,STAPLES,LD-AF-G1-D1-D6-08-E,30533,P3
8287,BLR_128178,82781.0,3.0,combo_9,LD-AJ-G2-A2-A10-10-C,4275,P3
12926,BLR_128178,962.0,2.0,SPICES&DAL,LD-AM-G1-A1-A13-15-B,2023,P2
13993,BLR_128178,3451.0,5.0,combo_6,LD-AM-G3-B3-B15-09-B,16730,P3
18071,BLR_128178,15650.0,2.0,FMCG_FOOD1,LD-AG-G1-B1-B7-07-F,11742,P3
19109,BLR_128178,5821.0,3.0,combo_8,LD-AF-G3-E3-E6-09-C,46698,P2
19144,BLR_128178,7485.0,3.0,combo_8,LD-AG-G3-D3-D7-18-E,34703,P2
22104,BLR_128178,90671.0,3.0,combo_8,LD-AB-G3-D3-D2-11-B,34130,P2
23895,BLR_128178,339.0,3.0,combo_11,LD-AN-G3-A3-A14-11-D,6997,P3
25559,BLR_128178,4257.0,17.0,SPICES&DAL,LD-AJ-G1-A1-A10-13-A,1878,P2
26456,BLR_128178,88529.0,2.0,CICO_D2,LD-AG-G2-D2-D7-01-D,33397,P2

In [ ]:
order.groupby('zone').agg(
    sku_count=('sku', 'count'),
    total_qty=('order_qty', 'sum')
).sort_values('sku_count', ascending=False)

            sku_count  total_qty
zone
combo_9           110      490.0
combo_11          109      276.0
combo_8           103      210.0
combo_6            88      208.0
CHOCOLATES         54      345.0
SPICES&DAL         50      196.0
FMCG_FOOD2         44      143.0
FMCG_FOOD1         32       76.0
combo_4            29       43.0
BISC_BAK           22      105.0
CICO_FD            21       66.0
combo_5            20       65.0
combo_2            20       32.0
STAPLES            20      226.0
REB_G1_FD          19       26.0
FRAGILE_FD         19       97.0
CICO_G2            18      487.0
H_STAPLES          17      136.0
HNK_LARGE          15       27.0
CICO_D2            15       44.0
combo_3            13       26.0
combo_7            11       14.0
HVAL_APPG1         11       23.0
combo_10           11       17.0
M&S_2               7       20.0
DP+DB               6       18.0
CICO_OIL            5       35.0
DIAPERS             4        9.0
OIL&GHEE_S          3       13.0
CD_CICO             2        3.0
REB_FD_G0           2        3.0
DL+CL               2       10.0
LIQUID_E0           1        3.0
combo_1             1        6.0

In [ ]:
order[['zone', 'bin', 'bin_rank']].sort_values('bin_rank', ascending=False).head(20)

              zone                  bin  bin_rank
628672     combo_1     HD-R9-G0-PL-01-G     47443
348912   HNK_LARGE            CH-MAS-03     47219
866926   HNK_LARGE                T1-83     47199
1226866  HNK_LARGE                T1-59     47175
1023576  HNK_LARGE                T1-49     47165
643403   HNK_LARGE                T1-45     47161
97893    HNK_LARGE                T1-36     47152
770454   HNK_LARGE                T1-34     47150
69289    HNK_LARGE                T1-33     47149
626803   HNK_LARGE                T1-26     47142
978850   HNK_LARGE                T1-13     47129
1090923  HNK_LARGE                T1-05     47121
796955   HNK_LARGE                T1-05     47121
929244   HNK_LARGE                T1-05     47121
768271   HNK_LARGE                T1-03     47119
612173   HNK_LARGE                T1-01     47117
767369     combo_8  LD-AA-G3-E3-E1-08-B     47087
919685     combo_8  LD-AC-G3-E3-E3-16-A     47020
418439     combo_8  LD-AC-G3-E3-E3-11-C     46992
1049424    combo_8  LD-AC-G3-E3-E3-09-D     46981

In [ ]:
df[['bin', 'bin_rank']].drop_duplicates().sort_values('bin_rank').head(300)

                         bin  bin_rank
20620     LD-AR-D0-D20-03-A3         0
114758    LD-AQ-C0-C19-10-A1         0
187355   LD-AB-G3-A3-A2-06-D         0
186908    LD-AR-C0-C20-11-A3         0
188122    LD-AR-C0-C20-15-A1         0
...                      ...       ...
1046978  PL-AC-G0-A0-A3-16-B       608
251574   PL-AC-G0-A0-A3-16-C       609
273      PL-AC-G0-A0-A3-16-D       610
1061998  PL-AD-G0-A0-A4-15-A       612
3301     PL-AD-G0-A0-A4-16-D       613

[300 rows x 2 columns]

In [ ]:
order.groupby('zone')['pods_per_picklist_in_that_zone'].first().sort_values(ascending=False)

zone
CD_CICO       7
CICO_D2       7
CICO_G2       7
CICO_FD       7
CICO_OIL      7
combo_4       6
FMCG_FOOD1    6
SPICES&DAL    6
REB_G1_FD     6
REB_FD_G0     6
combo_11      6
combo_6       6
combo_7       6
combo_10      6
BISC_BAK      4
CHOCOLATES    4
FMCG_FOOD2    4
M&S_2         4
combo_9       4
STAPLES       4
OIL&GHEE_S    4
combo_3       4
FRAGILE_FD    3
DIAPERS       3
DL+CL         3
DP+DB         3
combo_8       3
LIQUID_E0     3
H_STAPLES     3
HNK_LARGE     3
combo_5       3
HVAL_APPG1    1
combo_1       1
combo_2       1
Name: pods_per_picklist_in_that_zone, dtype: int64

In [ ]:
# Is it a static zone attribute, or does it vary order to order?
df.groupby('zone')['pods_per_picklist_in_that_zone'].nunique().describe()

count    38.0
mean      1.0
std       0.0
min       1.0
25%       1.0
50%       1.0
75%       1.0
max       1.0
Name: pods_per_picklist_in_that_zone, dtype: float64

In [ ]:
df.groupby('zone')['pods_per_picklist_in_that_zone'].agg(['min','max','nunique'])

            min  max  nunique
zone
ATTA          2    2        1
BISC_BAK      4    4        1
CD_CICO       7    7        1
CHOCOLATES    4    4        1
CICO_D2       7    7        1
CICO_FD       7    7        1
CICO_G2       7    7        1
CICO_OIL      7    7        1
DIAPERS       3    3        1
DL+CL         3    3        1
DP+DB         3    3        1
FMCG_FOOD1    6    6        1
FMCG_FOOD2    4    4        1
FRAGILE_FD    3    3        1
GOLD          1    1        1
HNK_LARGE     3    3        1
HVAL_APPG1    1    1        1
HVAL_APP_2    1    1        1
H_STAPLES     3    3        1
LIQUID_E0     3    3        1
M&S_2         4    4        1
OIL&GHEE_S    4    4        1
REB_FD_G0     6    6        1
REB_G1_FD     6    6        1
SAMPLE        6    6        1
SPICES&DAL    6    6        1
STAPLES       4    4        1
combo_1       1    1        1
combo_10      6    6        1
combo_11      6    6        1
combo_2       1    1        1
combo_3       4    4        1
combo_4       6    6        1
combo_5       3    3        1
combo_6       6    6        1
combo_7       6    6        1
combo_8       3    3        1
combo_9       4    4        1

In [ ]:
# Does it correlate with pick volume at all, or with something else?
zone_stats = df.groupby('zone').agg(
    pick_rows=('sku','count'),
    n_distinct_pods=('store_id','nunique'),   # actual distinct stores touching that zone
    reported_value=('pods_per_picklist_in_that_zone','first')
)
zone_stats[['pick_rows','n_distinct_pods','reported_value']].corr()

                 pick_rows  n_distinct_pods  reported_value
pick_rows         1.000000         0.169371        0.123178
n_distinct_pods   0.169371         1.000000        0.274391
reported_value    0.123178         0.274391        1.000000

In [ ]:
order_zone_count = (
    df.groupby('order_id')['zone']
    .nunique()
)

order_zone_count.describe()

count    1901.000000
mean       26.934771
std        12.354073
min         1.000000
25%        28.000000
50%        33.000000
75%        34.000000
max        37.000000
Name: zone, dtype: float64

In [ ]:
import pandas as pd
import numpy as np

# Make a working copy
df = df.copy()

# -----------------------------
# 1. Standardize column names
# -----------------------------
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(' ', '_')
)

# -----------------------------
# 2. Clean text columns
# -----------------------------
text_cols = [
    'location_code',
    'order_id',
    'sku',
    'bin',
    'zone',
    'order_tag',
    'store_id',
    'floor',
    'rack',
    'aisle',
    'pod_priority'
]

for col in text_cols:
    if col in df.columns:
        df[col] = df[col].astype('string').str.strip()

# -----------------------------
# 3. Convert dates
# -----------------------------
df['dt'] = pd.to_datetime(df['dt'], errors='coerce')
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

# -----------------------------
# 4. Convert numeric columns
# -----------------------------
numeric_cols = [
    'order_qty',
    'bin_rank',
    'pods_per_picklist_in_that_zone',
    'length_in_cm',
    'width_in_cm',
    'height_in_cm',
    'weight_in_grams'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# -----------------------------
# 5. Remove exact duplicates
# -----------------------------
df = df.drop_duplicates().reset_index(drop=True)

print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Duplicate rows:", df.duplicated().sum())
print("Missing values:")
print(df.isna().sum()[df.isna().sum() > 0])

Rows: 1281177
Columns: 20
Duplicate rows: 0
Missing values:
floor    6545
rack     6545
aisle    6545
dtype: int64

In [ ]:
for col in ['floor', 'rack', 'aisle']:
    df[col] = df[col].fillna('UNKNOWN')

In [ ]:
print("Missing values:")
print(df.isna().sum()[df.isna().sum() > 0])

Missing values:
Series([], dtype: int64)

In [ ]:
df.to_csv('formatted.csv')

In [ ]:
df['weight_kg'] = df['weight_in_grams'] / 1000

In [ ]:
df['volume_cm3'] = (
    df['length_in_cm'] *
    df['width_in_cm'] *
    df['height_in_cm']
)

In [ ]:
df['priority_num'] = (
    df['pod_priority']
    .str.extract(r'(\d+)')[0]
    .astype('Int64')
)

In [ ]:
order_zone = (
    df.groupby(['order_id', 'zone'], as_index=False)
      .agg(
          order_date=('order_date', 'min'),
          store_id=('store_id', 'nunique'),
          priority_num=('priority_num', 'min'),

          sku_lines=('sku', 'count'),
          unique_skus=('sku', 'nunique'),

          total_qty=('order_qty', 'sum'),

          unique_bins=('bin', 'nunique'),

          total_weight_kg=('weight_kg', 'sum'),
          total_volume_cm3=('volume_cm3', 'sum'),

          zone_complexity_tier=(
              'pods_per_picklist_in_that_zone',
              'first'
          )
      )
)

order_zone.head()

,order_id,zone,order_date,store_id,priority_num,sku_lines,unique_skus,total_qty,unique_bins,total_weight_kg,total_volume_cm3,zone_complexity_tier
0,BLR_120033,BISC_BAK,2025-11-14,1,5,1,1,2.0,1,0.375,1805.000,4
1,BLR_120033,CHOCOLATES,2025-11-14,1,5,2,2,4.0,2,0.287,1351.286,4
2,BLR_120033,DIAPERS,2025-11-14,1,5,1,1,1.0,1,0.810,8615.520,3
3,BLR_120033,DP+DB,2025-11-14,1,5,4,4,4.0,4,8.148,11185.250,3
4,BLR_120033,FMCG_FOOD1,2025-11-14,1,5,1,1,2.0,1,0.200,2000.000,6

In [ ]:
order_zone['store_count'] = order_zone['store_id']

order_zone['store_count'].value_counts().sort_index()

store_count
1    50513
2      690
Name: count, dtype: int64

In [ ]:
order_zone['travel_seconds'] = (
    order_zone['unique_bins'] * 30
)

order_zone['pickup_seconds'] = (
    order_zone['total_qty'] * 5
)

order_zone['base_work_seconds'] = (
    order_zone['travel_seconds'] +
    order_zone['pickup_seconds']
)

order_zone['base_work_minutes'] = (
    order_zone['base_work_seconds'] / 60
)

In [ ]:
order_zone['picklists_by_qty'] = np.ceil(
    order_zone['total_qty'] / 2000
).astype(int)

order_zone['picklists_by_weight'] = np.ceil(
    order_zone['total_weight_kg'] / 200
).astype(int)

order_zone['picklists_required'] = (
    order_zone[['picklists_by_qty', 'picklists_by_weight']]
    .max(axis=1)
)

In [ ]:
order_zone['workload_level'] = pd.qcut(
    order_zone['base_work_minutes'],
    q=4,
    labels=['Low', 'Medium', 'High', 'Very High'],
    duplicates='drop'
)

In [ ]:
order_zone.columns.tolist()

['order_id',
 'zone',
 'order_date',
 'store_id',
 'priority_num',
 'sku_lines',
 'unique_skus',
 'total_qty',
 'unique_bins',
 'total_weight_kg',
 'total_volume_cm3',
 'zone_complexity_tier',
 'store_count',
 'travel_seconds',
 'pickup_seconds',
 'base_work_seconds',
 'base_work_minutes',
 'picklists_by_qty',
 'picklists_by_weight',
 'picklists_required',
 'workload_level']

In [ ]:
print(df.columns)

Index(['dt', 'order_date', 'location_code', 'order_id', 'sku', 'order_qty',
       'bin', 'zone', 'bin_rank', 'order_tag', 'store_id', 'floor', 'rack',
       'aisle', 'pods_per_picklist_in_that_zone', 'length_in_cm',
       'width_in_cm', 'height_in_cm', 'weight_in_grams', 'pod_priority',
       'weight_kg', 'volume_cm3', 'priority_num'],
      dtype='object')

In [ ]:
zone_workload = df.copy()

print(zone_workload.shape)
print(zone_workload.columns.tolist())

(1281177, 23)
['dt', 'order_date', 'location_code', 'order_id', 'sku', 'order_qty', 'bin', 'zone', 'bin_rank', 'order_tag', 'store_id', 'floor', 'rack', 'aisle', 'pods_per_picklist_in_that_zone', 'length_in_cm', 'width_in_cm', 'height_in_cm', 'weight_in_grams', 'pod_priority', 'weight_kg', 'volume_cm3', 'priority_num']

In [ ]:
zone_workload = (
    df.groupby(['order_id', 'zone'])
      .agg(
          order_date=('order_date', 'first'),
          store_id=('store_id', 'first'),
          priority_num=('priority_num', 'first'),

          sku_lines=('sku', 'count'),
          unique_skus=('sku', 'nunique'),
          total_qty=('order_qty', 'sum'),
          unique_bins=('bin', 'nunique'),

          total_weight_kg=('weight_kg', 'sum'),
          total_volume_cm3=('volume_cm3', 'sum'),

          zone_complexity_tier=(
              'pods_per_picklist_in_that_zone', 'first'
          )
      )
      .reset_index()
)

In [ ]:
zone_workload.head()

,order_id,zone,order_date,store_id,priority_num,sku_lines,unique_skus,total_qty,unique_bins,total_weight_kg,total_volume_cm3,zone_complexity_tier
0,BLR_120033,BISC_BAK,2025-11-14,401004.0,5,1,1,2.0,1,0.375,1805.000,4
1,BLR_120033,CHOCOLATES,2025-11-14,401004.0,5,2,2,4.0,2,0.287,1351.286,4
2,BLR_120033,DIAPERS,2025-11-14,401004.0,5,1,1,1.0,1,0.810,8615.520,3
3,BLR_120033,DP+DB,2025-11-14,401004.0,5,4,4,4.0,4,8.148,11185.250,3
4,BLR_120033,FMCG_FOOD1,2025-11-14,401004.0,5,1,1,2.0,1,0.200,2000.000,6

In [ ]:
zone_workload['travel_seconds'] = zone_workload['unique_bins'] * 30

zone_workload['pickup_seconds'] = zone_workload['total_qty'] * 5

zone_workload['base_work_seconds'] = (
    zone_workload['travel_seconds']
    + zone_workload['pickup_seconds']
)

zone_workload['base_work_minutes'] = (
    zone_workload['base_work_seconds'] / 60
)

In [ ]:
zone_workload[
    [
        'order_id',
        'zone',
        'unique_bins',
        'total_qty',
        'travel_seconds',
        'pickup_seconds',
        'base_work_seconds',
        'base_work_minutes'
    ]
].head(10)

,order_id,zone,unique_bins,total_qty,travel_seconds,pickup_seconds,base_work_seconds,base_work_minutes
0,BLR_120033,BISC_BAK,1,2.0,30,10.0,40.0,0.666667
1,BLR_120033,CHOCOLATES,2,4.0,60,20.0,80.0,1.333333
2,BLR_120033,DIAPERS,1,1.0,30,5.0,35.0,0.583333
3,BLR_120033,DP+DB,4,4.0,120,20.0,140.0,2.333333
4,BLR_120033,FMCG_FOOD1,1,2.0,30,10.0,40.0,0.666667
5,BLR_120033,FMCG_FOOD2,4,6.0,120,30.0,150.0,2.500000
6,BLR_120033,HNK_LARGE,1,2.0,30,10.0,40.0,0.666667
7,BLR_120033,combo_11,6,8.0,180,40.0,220.0,3.666667
8,BLR_120033,combo_3,2,2.0,60,10.0,70.0,1.166667
9,BLR_120033,combo_4,12,12.0,360,60.0,420.0,7.000000

In [ ]:
print(zone_workload.columns.tolist())
print(zone_workload.shape)

['order_id', 'zone', 'order_date', 'store_id', 'priority_num', 'sku_lines', 'unique_skus', 'total_qty', 'unique_bins', 'total_weight_kg', 'total_volume_cm3', 'zone_complexity_tier', 'travel_seconds', 'pickup_seconds', 'base_work_seconds', 'base_work_minutes']
(51203, 16)

In [ ]:
print(zone_workload[['order_id', 'zone']].duplicated().sum())
print(zone_workload['order_id'].nunique())
print(zone_workload['zone'].nunique())

0
1901
38

In [ ]:
import numpy as np

np.random.seed(42)

zone_workload['simulated_work_seconds'] = (
    zone_workload['base_work_seconds'] *
    (1 + np.random.normal(0, 0.12, len(zone_workload)))
).clip(lower=10)

In [ ]:
df.groupby('order_id')['pod_priority'].nunique().value_counts()

pod_priority
1    1876
2      25
Name: count, dtype: int64

In [ ]:
zone_workload.to_csv('zone_workload_clean.csv', index=False)

In [ ]:
import os

print(os.getcwd())
print(os.path.exists("zone_workload_clean.csv"))
print(os.path.abspath("zone_workload_clean.csv"))

/content
True
/content/zone_workload_clean.csv

In [ ]:
print(df.columns.tolist())
print(df.shape)
print(zone_workload.columns.tolist())
print(zone_workload.shape)
zone_workload.head()

['dt', 'order_date', 'location_code', 'order_id', 'sku', 'order_qty', 'bin', 'zone', 'bin_rank', 'order_tag', 'store_id', 'floor', 'rack', 'aisle', 'pods_per_picklist_in_that_zone', 'length_in_cm', 'width_in_cm', 'height_in_cm', 'weight_in_grams', 'pod_priority', 'weight_kg', 'volume_cm3', 'priority_num']
(1281177, 23)
['order_id', 'zone', 'order_date', 'store_id', 'priority_num', 'sku_lines', 'unique_skus', 'total_qty', 'unique_bins', 'total_weight_kg', 'total_volume_cm3', 'zone_complexity_tier', 'travel_seconds', 'pickup_seconds', 'base_work_seconds', 'base_work_minutes', 'simulated_work_seconds']
(51203, 17)

,order_id,zone,order_date,store_id,priority_num,sku_lines,unique_skus,total_qty,unique_bins,total_weight_kg,total_volume_cm3,zone_complexity_tier,travel_seconds,pickup_seconds,base_work_seconds,base_work_minutes,simulated_work_seconds
0,BLR_120033,BISC_BAK,2025-11-14,401004.0,5,1,1,2.0,1,0.375,1805.000,4,30,10.0,40.0,0.666667,42.384228
1,BLR_120033,CHOCOLATES,2025-11-14,401004.0,5,2,2,4.0,2,0.287,1351.286,4,60,20.0,80.0,1.333333,78.672663
2,BLR_120033,DIAPERS,2025-11-14,401004.0,5,1,1,1.0,1,0.810,8615.520,3,30,5.0,35.0,0.583333,37.720292
3,BLR_120033,DP+DB,2025-11-14,401004.0,5,4,4,4.0,4,8.148,11185.250,3,120,20.0,140.0,2.333333,165.586902
4,BLR_120033,FMCG_FOOD1,2025-11-14,401004.0,5,1,1,2.0,1,0.200,2000.000,6,30,10.0,40.0,0.666667,38.876064

In [ ]:
zone_workload.to_csv('/content/drive/MyDrive/Colab Notebooks/Warehouse/zone_workload_clean.csv', index=False)